version: '3'
services:
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  consul1:
    image: "consul:0.9.3"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53"